Added support for copilot-cli

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -10,14 +10,32 @@ source "${plugin_dir}/lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
-# TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+uname_s="$(uname -s)"
+uname_m="$(uname -m)"
+os=""
+
+case "$uname_s" in
+Darwin) os="darwin" ;;
+Linux) os="linux" ;;
+*) fail "OS not supported: $uname_s" ;;
+esac
+
+case "$uname_m" in
+aarch64 | arm64) arch="arm64" ;;
+x86_64) arch="x64" ;;
+*) fail "Architecture not supported: $uname_m" ;;
+esac
+
+os="${os}-${arch}"
+
+release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$os-$ASDF_INSTALL_VERSION.tar.gz"
 
 # Download tar.gz file to the download directory
-download_release "$ASDF_INSTALL_VERSION" "$release_file"
+download_release "$ASDF_INSTALL_VERSION" "$release_file" "$os"
 
 #  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+echo "* Extracting $release_file to $ASDF_DOWNLOAD_PATH"
+tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
 
 # Remove the tar.gz file since we don't need to keep it
 rm "$release_file"
